-- #1 List the case number, type of crime and community area for all crimes in community area number 18.
-- select CR.CASE_NUMBER, CR.PRIMARY_TYPE as CRIME_TYPE, CR.COMMUNITY_AREA_NUMBER, CD.COMMUNITY_AREA_NAME from CHICAGO_CRIME_DATA CR INNER JOIN CENSUS_DATA CD
--ON CR.COMMUNITY_AREA_NUMBER = CD.COMMUNITY_AREA_NUMBER where CR.COMMUNITY_AREA_NUMBER=18

-- #2 List all crimes that took place at a school. Include case number, crime type and community name.
--select CR.CASE_NUMBER, CR.PRIMARY_TYPE as CRIME_TYPE, CR.COMMUNITY_AREA_NUMBER, CR.LOCATION_DESCRIPTION, 
--CD.COMMUNITY_AREA_NAME from CHICAGO_CRIME_DATA CR INNER JOIN CENSUS_DATA CD
--ON CR.COMMUNITY_AREA_NUMBER = CD.COMMUNITY_AREA_NUMBER where CR.LOCATION_DESCRIPTION LIKE '%SCHOOL%';

--#2 Alternate
--select CR.CASE_NUMBER, CR.PRIMARY_TYPE as CRIME_TYPE, CR.COMMUNITY_AREA_NUMBER, CR.LOCATION_DESCRIPTION, 
--CD.COMMUNITY_AREA_NAME from CHICAGO_CRIME_DATA CR LEFT JOIN CENSUS_DATA CD
--ON CR.COMMUNITY_AREA_NUMBER = CD.COMMUNITY_AREA_NUMBER WHERE CR.LOCATION_DESCRIPTION LIKE '%SCHOOL%'

--#3 For the communities of Oakland, Armour Square, Edgewater and CHICAGO list the associated community_area_numbers 
--and the case_numbers.
--select CD.COMMUNITY_AREA_NUMBER, CD.COMMUNITY_AREA_NAME, 
--CR.CASE_NUMBER from CENSUS_DATA CD LEFT JOIN CHICAGO_CRIME_DATA CR 
--ON CD.COMMUNITY_AREA_NUMBER = CR.COMMUNITY_AREA_NUMBER where 
--(CD.COMMUNITY_AREA_NAME  LIKE '%Oakland%' or
--CD.COMMUNITY_AREA_NAME  LIKE '%Armour Square%' or 
--CD.COMMUNITY_AREA_NAME  LIKE '%Edgewater%');

--Alternate
select CD.COMMUNITY_AREA_NUMBER, CD.COMMUNITY_AREA_NAME, 
CR.CASE_NUMBER from CENSUS_DATA CD FULL JOIN CHICAGO_CRIME_DATA CR 
ON CD.COMMUNITY_AREA_NUMBER = CR.COMMUNITY_AREA_NUMBER where 
(CD.COMMUNITY_AREA_NAME  LIKE '%Oakland%' or
CD.COMMUNITY_AREA_NAME  LIKE '%Armour Square%' or 
CD.COMMUNITY_AREA_NAME  LIKE '%Edgewater%');